
LIBS = 
OBJS = 3dshax_parsedebug.o
CXXFLAGS = -Wall -Os -I.
CFLAGS = $(CXXFLAGS)
OUTPUT = 3dshax_parsedebug
CC = gcc 

ifneq ($(strip $(NIX)),)
	CFLAGS	:=	$(CFLAGS) -DNIX
endif

ifneq ($(strip $(WIN32)),)
	CFLAGS	:=	$(CFLAGS) -D_WIN32
endif

main: $(OBJS)
	$(CC) -o $(OUTPUT) $(OBJS) $(LIBS)
clean:
	rm -rf $(OUTPUT) $(OBJS)
